name = "percworld modpack"
author = "percworld"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61c65caad4e0e356bc1434e9c4a54997f31d30b2712b5348372f5cbb0c72afdc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
