name = "percworld modpack"
author = "percworld"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b29690fef42bfc2d5d50c512d22bec5484c31bd58971cfe7576c782cae511584"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
