name = "percworld modpack"
author = "percworld"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c6b9450199301b72fceb915c54cf4f0bf615eb87d928f747687b6ea282997ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
